'use client';
import React, { useState } from 'react';
import JSZip from 'jszip';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import type {
  MessageCodeGenerateResponse,
  MessageCodeDAGResponse,
  ERuleResponse,
} from '@/lib/types';

interface GeneratedOutputProps {
  result: MessageCodeGenerateResponse;
  dagResult: MessageCodeDAGResponse | null;
  eRulesResult: ERuleResponse | null;
  onGenerateDAG: () => void;
  onGenerateERules: () => void;
  onSaveToKnowledge: () => void;
  onStartOver: () => void;
  dagLoading: boolean;
  eRulesLoading: boolean;
  saveLoading: boolean;
  saved: boolean;
  messageCode: string;
}

type ActiveTab = 'sql' | 'changes' | 'dag' | 'erules';
type ERulesSubTab = 'general' | 'rule' | 'cdp_select' | 'big_query' | 'erule_json';

function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildReadme(
  messageCode: string,
  result: MessageCodeGenerateResponse,
  dagResult: MessageCodeDAGResponse | null,
): string {
  const lines: string[] = [
    `# ${messageCode}`,
    '',
    `**Template Used:** ${result.template_name} (\`${result.template_used}\`)`,
    '',
    '## Logic Summary',
    '',
    result.logic_summary,
    '',
    '## Changes from Template',
    '',
  ];
  for (const change of result.changes) {
    lines.push(`- **${change.section}**: ${change.description}`);
  }
  if (result.warnings.length > 0) {
    lines.push('', '## Warnings / Review Items', '');
    for (const w of result.warnings) lines.push(`- ${w}`);
  }
  if (dagResult) {
    lines.push('', '## DAG Information', '', `- **DAG ID:** ${dagResult.dag_id}`, `- **Schedule (cron):** \`${dagResult.cron}\``, `- **Filename:** ${dagResult.filename}`);
  }
  lines.push('', '---', `Generated by Message Code Builder on ${new Date().toISOString().split('T')[0]}`);
  return lines.join('\n');
}

const DownloadIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

const Spinner = () => (
  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
);

export function GeneratedOutput({
  result,
  dagResult,
  eRulesResult,
  onGenerateDAG,
  onGenerateERules,
  onSaveToKnowledge,
  onStartOver,
  dagLoading,
  eRulesLoading,
  saveLoading,
  saved,
  messageCode,
}: GeneratedOutputProps) {
  const [activeTab, setActiveTab] = useState<ActiveTab>('sql');
  const [eRulesSubTab, setERulesSubTab] = useState<ERulesSubTab>('general');
  const [copied, setCopied] = useState<string | null>(null);

  const baseFilename = (messageCode || 'message_code').toLowerCase().replace(/[^a-z0-9_]/g, '_');

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownloadSQL = () => downloadFile(result.sql, `${baseFilename}.sql`);

  const handleDownloadDAG = () => {
    if (!dagResult) return;
    downloadFile(dagResult.dag_code, dagResult.filename || `${baseFilename}_dag.py`);
  };

  const handleDownloadERules = () => {
    if (!eRulesResult) return;
    downloadFile(JSON.stringify(eRulesResult.erule_json, null, 2), `${baseFilename}_erule.json`);
  };

  const handleDownloadAll = async () => {
    const zip = new JSZip();
    zip.file(`${baseFilename}.sql`, result.sql);
    if (dagResult) {
      zip.file(dagResult.filename || `${baseFilename}_dag.py`, dagResult.dag_code);
    }
    if (eRulesResult) {
      zip.file(`${baseFilename}_erule.json`, JSON.stringify(eRulesResult.erule_json, null, 2));
      zip.file(`${baseFilename}_cdp_select.sql`, eRulesResult.cdp_select);
    }
    zip.file(`${baseFilename}_README.md`, buildReadme(messageCode, result, dagResult));
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${baseFilename}_package.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const tabs: { id: ActiveTab; label: string }[] = [
    { id: 'sql', label: 'SQL' },
    { id: 'changes', label: `Changes (${result.changes.length})` },
    { id: 'dag', label: 'DAG' },
    { id: 'erules', label: 'eRules' },
  ];

  const eRulesSubTabs: { id: ERulesSubTab; label: string }[] = [
    { id: 'general', label: 'General' },
    { id: 'rule', label: 'Rule' },
    { id: 'cdp_select', label: 'CDP Select' },
    { id: 'big_query', label: 'Big Query' },
    { id: 'erule_json', label: 'Page-a-Rule' },
  ];

  return (
    <div className="space-y-4">
      {/* Header with logic summary */}
      <Card>
        <div className="flex items-start gap-3 mb-3">
          <div className="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-950 flex items-center justify-center flex-shrink-0">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#2563EB" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z" />
              <polyline points="13 2 13 9 20 9" />
            </svg>
          </div>
          <div className="flex-1">
            <h3 className="text-sm font-bold text-text-primary">Generated Message Code</h3>
            <p className="text-xs text-text-muted mt-0.5">
              Based on template: <span className="font-medium">{result.template_name}</span>
            </p>
          </div>
        </div>
        <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-3 mb-3">
          <p className="text-xs text-text-secondary"><span className="font-medium">Logic:</span> {result.logic_summary}</p>
        </div>
        {result.warnings.length > 0 && (
          <div className="space-y-2 mb-3">
            {result.warnings.map((w, i) => (
              <div key={i} className="flex items-start gap-2 p-2 rounded-lg bg-amber-50 dark:bg-amber-950 border border-amber-200 dark:border-amber-800">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#d97706" strokeWidth="2" className="flex-shrink-0 mt-0.5">
                  <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
                  <line x1="12" y1="9" x2="12" y2="13" />
                  <line x1="12" y1="17" x2="12.01" y2="17" />
                </svg>
                <p className="text-xs text-amber-800 dark:text-amber-200">{w}</p>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Tabbed content */}
      <Card padding={false}>
        <div className="flex border-b border-surface-border">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2.5 text-sm font-medium transition-colors ${
                activeTab === tab.id
                  ? 'text-brand-blue border-b-2 border-brand-blue'
                  : 'text-text-muted hover:text-text-primary'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="p-4">
          {/* === SQL TAB === */}
          {activeTab === 'sql' && (
            <div>
              <div className="flex justify-end gap-2 mb-2">
                <Button variant="ghost" size="sm" onClick={() => copyToClipboard(result.sql, 'sql')}>
                  {copied === 'sql' ? 'Copied!' : 'Copy SQL'}
                </Button>
                <Button variant="ghost" size="sm" onClick={handleDownloadSQL}>
                  <span className="flex items-center gap-1.5"><DownloadIcon /> Download SQL</span>
                </Button>
              </div>
              <pre className="p-4 bg-gray-900 text-green-400 text-xs rounded-lg overflow-x-auto max-h-[500px] overflow-y-auto leading-relaxed">
                <code>{result.sql}</code>
              </pre>
            </div>
          )}

          {/* === CHANGES TAB === */}
          {activeTab === 'changes' && (
            <div className="space-y-3">
              {result.changes.map((change, i) => (
                <div key={i} className="p-3 rounded-lg border border-surface-border">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="px-2 py-0.5 text-[10px] font-medium rounded bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">{change.section}</span>
                  </div>
                  <p className="text-xs text-text-secondary">{change.description}</p>
                </div>
              ))}
            </div>
          )}

          {/* === DAG TAB === */}
          {activeTab === 'dag' && (
            <div>
              {dagResult ? (
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-text-muted">DAG ID: <span className="font-mono font-medium text-text-primary">{dagResult.dag_id}</span></span>
                      <span className="text-xs text-text-muted">Cron: <span className="font-mono font-medium text-text-primary">{dagResult.cron}</span></span>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="ghost" size="sm" onClick={() => copyToClipboard(dagResult.dag_code, 'dag')}>
                        {copied === 'dag' ? 'Copied!' : 'Copy DAG'}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={handleDownloadDAG}>
                        <span className="flex items-center gap-1.5"><DownloadIcon /> Download DAG</span>
                      </Button>
                    </div>
                  </div>
                  <pre className="p-4 bg-gray-900 text-green-400 text-xs rounded-lg overflow-x-auto max-h-[500px] overflow-y-auto leading-relaxed">
                    <code>{dagResult.dag_code}</code>
                  </pre>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-12">
                  <p className="text-sm text-text-muted mb-4">Generate the Airflow DAG for scheduling this message code</p>
                  <Button variant="primary" onClick={onGenerateDAG} disabled={dagLoading}>
                    {dagLoading ? <span className="flex items-center gap-2"><Spinner /> Generating DAG...</span> : 'Generate Airflow DAG'}
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* === eRULES TAB === */}
          {activeTab === 'erules' && (
            <div>
              {eRulesResult ? (
                <div>
                  {/* Header bar mimicking MCS Rule Builder */}
                  <div className="flex items-center justify-between mb-4 pb-3 border-b border-surface-border">
                    <div className="flex items-center gap-3">
                      <span className="text-xs font-bold text-red-600 uppercase tracking-wide">MCS Rule Builder</span>
                      <span className="text-xs text-text-muted">Target ID: <span className="font-mono font-medium text-text-primary">{eRulesResult.target_id}</span></span>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="ghost" size="sm" onClick={() => copyToClipboard(JSON.stringify(eRulesResult.erule_json, null, 2), 'erule')}>
                        {copied === 'erule' ? 'Copied!' : 'Copy eRule JSON'}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={handleDownloadERules}>
                        <span className="flex items-center gap-1.5"><DownloadIcon /> Download eRule</span>
                      </Button>
                    </div>
                  </div>

                  {/* Sub-tabs matching the screenshot */}
                  <div className="flex gap-1 mb-4 border-b border-surface-border">
                    {eRulesSubTabs.map((st) => (
                      <button
                        key={st.id}
                        onClick={() => setERulesSubTab(st.id)}
                        className={`px-3 py-2 text-xs font-medium transition-colors rounded-t ${
                          eRulesSubTab === st.id
                            ? 'text-red-600 border-b-2 border-red-600 bg-red-50 dark:bg-red-950'
                            : 'text-text-muted hover:text-text-primary'
                        }`}
                      >
                        {st.label}
                      </button>
                    ))}
                  </div>

                  {/* Sub-tab content */}
                  {eRulesSubTab === 'general' && (
                    <div className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="text-xs font-medium text-text-muted">Name</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border flex items-center gap-2">
                            <input type="checkbox" checked={eRulesResult.general.enabled} readOnly className="accent-blue-600" />
                            <span className="font-mono text-text-primary">{eRulesResult.general.name}</span>
                          </div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Description</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border text-text-primary">{eRulesResult.general.description}</div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Base</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border text-text-primary">{eRulesResult.general.base}</div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Target ID</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border font-mono text-text-primary">{eRulesResult.general.target_id}</div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Campaign</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border text-text-primary">{eRulesResult.general.campaign}</div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Pillars</label>
                          <div className="mt-1 flex items-center gap-2">
                            {eRulesResult.general.pillars.map((p) => (
                              <span key={p} className="px-2 py-1 text-xs rounded bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300 font-medium">{p}</span>
                            ))}
                          </div>
                        </div>
                        <div>
                          <label className="text-xs font-medium text-text-muted">Status</label>
                          <div className="mt-1 px-3 py-2 text-sm bg-amber-50 dark:bg-amber-950 rounded-lg border border-amber-200 dark:border-amber-800 text-amber-700 dark:text-amber-300 font-medium">{eRulesResult.general.status}</div>
                        </div>
                      </div>
                      <div className="border-t border-surface-border pt-4 mt-4">
                        <h4 className="text-xs font-bold text-text-primary mb-3">Include / Exclude</h4>
                        <div className="grid grid-cols-2 gap-4">
                          <div>
                            <label className="text-xs font-medium text-text-muted">Include Target Groups</label>
                            <div className="mt-1 px-3 py-2 text-xs bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border text-text-muted min-h-[36px]">
                              {eRulesResult.general.include_target_groups.length > 0 ? eRulesResult.general.include_target_groups.join(', ') : 'None'}
                            </div>
                          </div>
                          <div>
                            <label className="text-xs font-medium text-text-muted">Exclude Target Groups</label>
                            <div className="mt-1 px-3 py-2 text-xs bg-gray-50 dark:bg-gray-900 rounded-lg border border-surface-border text-text-muted min-h-[36px]">
                              {eRulesResult.general.exclude_target_groups.length > 0 ? eRulesResult.general.exclude_target_groups.join(', ') : 'None'}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {eRulesSubTab === 'rule' && (
                    <div>
                      <div className="flex gap-4 mb-3">
                        <button className="text-xs font-medium text-text-primary border-b-2 border-brand-blue pb-1">Basic</button>
                        <button className="text-xs font-medium text-text-muted pb-1">Advanced</button>
                      </div>
                      <div className="overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="bg-gray-900 text-white">
                              <th className="px-3 py-2 text-left font-medium w-12"></th>
                              <th className="px-3 py-2 text-left font-medium">Variable</th>
                              <th className="px-3 py-2 text-left font-medium w-24">Operator</th>
                              <th className="px-3 py-2 text-left font-medium">Value</th>
                              <th className="px-3 py-2 text-left font-medium w-20">Root Level</th>
                              <th className="px-3 py-2 text-right font-medium w-16">Join</th>
                            </tr>
                          </thead>
                          <tbody>
                            {eRulesResult.rules.map((rule, i) => (
                              <tr key={i} className={`border-b border-surface-border ${i % 2 === 0 ? 'bg-white dark:bg-gray-950' : 'bg-gray-50 dark:bg-gray-900'}`}>
                                <td className="px-3 py-2 font-mono font-bold text-red-600">{rule.id}</td>
                                <td className="px-3 py-2 font-mono text-text-primary">{rule.variable}</td>
                                <td className="px-3 py-2 text-text-secondary">{rule.operator}</td>
                                <td className="px-3 py-2 font-mono text-text-primary max-w-[300px] truncate" title={rule.value}>{rule.value}</td>
                                <td className="px-3 py-2 text-text-secondary">{rule.root_level}</td>
                                <td className="px-3 py-2 text-right">
                                  <span className={`px-2 py-0.5 text-[10px] font-bold rounded ${rule.join === 'AND' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-300'}`}>
                                    {rule.join}
                                  </span>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  {eRulesSubTab === 'cdp_select' && (
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className="text-sm font-bold text-text-primary">CDP Select Statement</h4>
                        <div className="flex gap-2">
                          <Button variant="ghost" size="sm" onClick={() => copyToClipboard(eRulesResult.cdp_select, 'cdp')}>
                            {copied === 'cdp' ? 'Copied!' : 'Copy CDP'}
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => downloadFile(eRulesResult.cdp_select, `${baseFilename}_cdp_select.sql`)}>
                            <span className="flex items-center gap-1.5"><DownloadIcon /> Download</span>
                          </Button>
                        </div>
                      </div>
                      <pre className="p-4 bg-gray-900 text-green-400 text-xs rounded-lg overflow-x-auto max-h-[400px] overflow-y-auto leading-relaxed">
                        <code>{eRulesResult.cdp_select}</code>
                      </pre>
                    </div>
                  )}

                  {eRulesSubTab === 'big_query' && (
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className="text-sm font-bold text-text-primary">Big Query</h4>
                        <Button variant="ghost" size="sm" onClick={() => copyToClipboard(result.sql, 'bq')}>
                          {copied === 'bq' ? 'Copied!' : 'Copy SQL'}
                        </Button>
                      </div>
                      <pre className="p-4 bg-gray-900 text-green-400 text-xs rounded-lg overflow-x-auto max-h-[400px] overflow-y-auto leading-relaxed">
                        <code>{result.sql}</code>
                      </pre>
                    </div>
                  )}

                  {eRulesSubTab === 'erule_json' && (
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <h4 className="text-sm font-bold text-text-primary">e-Rule</h4>
                        <div className="flex gap-2">
                          <Button variant="ghost" size="sm" onClick={() => copyToClipboard(JSON.stringify(eRulesResult.erule_json, null, 2), 'erule_json')}>
                            {copied === 'erule_json' ? 'Copied!' : 'Copy JSON'}
                          </Button>
                          <Button variant="ghost" size="sm" onClick={handleDownloadERules}>
                            <span className="flex items-center gap-1.5"><DownloadIcon /> Download</span>
                          </Button>
                        </div>
                      </div>
                      <pre className="p-4 bg-gray-900 text-green-400 text-xs rounded-lg overflow-x-auto max-h-[500px] overflow-y-auto leading-relaxed">
                        <code>{JSON.stringify(eRulesResult.erule_json, null, 2)}</code>
                      </pre>
                    </div>
                  )}
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-12">
                  <div className="w-12 h-12 rounded-xl bg-red-50 dark:bg-red-950 flex items-center justify-center mb-4">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#dc2626" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M12 20h9" /><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
                    </svg>
                  </div>
                  <p className="text-sm font-medium text-text-primary mb-1">Generate eRules Output</p>
                  <p className="text-xs text-text-muted mb-4 text-center max-w-sm">
                    Generate the MCS Rule Builder format including General, Rule table, CDP Select, and Page-a-Rule JSON
                  </p>
                  <Button variant="primary" onClick={onGenerateERules} disabled={eRulesLoading}>
                    {eRulesLoading ? <span className="flex items-center gap-2"><Spinner /> Generating eRules...</span> : 'Generate eRules'}
                  </Button>
                </div>
              )}
            </div>
          )}
        </div>
      </Card>

      {/* Actions */}
      <div className="flex items-center justify-between">
        <Button variant="outline" onClick={onStartOver}>
          Start Over
        </Button>
        <div className="flex gap-3">
          <Button variant="outline" onClick={handleDownloadAll}>
            <span className="flex items-center gap-1.5"><DownloadIcon /> Download All (.zip)</span>
          </Button>
          <Button variant="primary" onClick={onSaveToKnowledge} disabled={saveLoading || saved}>
            {saved ? 'Saved to Knowledge Base' : saveLoading ? 'Saving...' : 'Save to Knowledge Base'}
          </Button>
        </div>
      </div>
    </div>
  );
}
